name: Full LeetCode Sync

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout default branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Sync LeetCode to GitHub
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GH_PAT }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: submissions
          commit-branch: leetcode-sync-temp 
          verbose: true
          commit-header: '[LeetCode Sync]'
