name: Full LeetCode Sync

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Create and switch to a new branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b leetcode-sync-temp

      - name: Sync LeetCode to GitHub
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GH_PAT }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: submissions
          verbose: true
          commit-header: '[LeetCode Sync]'

      - name: Push new branch to remote
        run: |
          git push origin leetcode-sync-temp
