name: Daily LeetCode Sync

on:
  schedule:
    - cron: '59 17 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          ref: main
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0
          persist-credentials: false

      - name: Set Git Identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Sync LeetCode to GitHub
        uses: joshcai/leetcode-sync@v1.7
        with:
          github-token: ${{ secrets.GH_PAT }}
          leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
          leetcode-session: ${{ secrets.LEETCODE_SESSION }}
          destination-folder: submissions
          verbose: true
          commit-header: '[LeetCode Sync]'
