name: PAT Push Test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Create test file
        run: echo "Test commit at $(date)" > test.txt
      - name: Commit & Push
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add test.txt
          git commit -m "PAT push test"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
